# Generated by Django 5.0.2 on 2024-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_addevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevents',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
