# Generated by Django 5.0.2 on 2024-03-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_addevents_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevents',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
