# Generated by Django 5.0.2 on 2024-03-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_addevents_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.companyregister'),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='credit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='persons',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventbook',
            name='status',
            field=models.CharField(default='BOOKED', max_length=100, null=True),
        ),
    ]
