# Generated by Django 5.0.2 on 2024-03-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_eventbook_company_id_eventbook_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbook',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
